# Generated by Django 3.1.2 on 2020-11-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='note_explain',
            field=models.TextField(verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='worn_explain',
            field=models.TextField(verbose_name='설명'),
        ),
    ]
