# Generated by Django 3.1.2 on 2020-11-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0002_auto_20201105_1947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': (('load_data', 'Can load data'),)},
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(default='<django.db.models.fields.CharField>@ksa.hs.kr', max_length=254),
        ),
    ]
