# Generated by Django 3.1.3 on 2020-11-29 04:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0002_auto_20201126_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='views',
        ),
        migrations.AddField(
            model_name='offer',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='notify_books',
            field=models.ManyToManyField(blank=True, to='ksa_books_app.Book', verbose_name='원하는 책'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='notify_comment',
            field=models.BooleanField(default=True, verbose_name='자신에게 댓글을 썼을 때'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='notify_new_offer',
            field=models.BooleanField(default=True, verbose_name='원하는 책이 올라왔을 때'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='notify_new_want',
            field=models.BooleanField(default=True, verbose_name='자신의 책을 누군가 구매 신청했을 때'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='notify_sold_to_other',
            field=models.BooleanField(default=True, verbose_name='구매 신청한 책이 다른 사람에게 판매되었을 때'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='notify_sold_to_user',
            field=models.BooleanField(default=True, verbose_name='자신에게 책을 판매했을 때'),
        ),
    ]
