# Generated by Django 3.1.2 on 2020-11-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0003_auto_20201106_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
