# Generated by Django 3.1.3 on 2020-11-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0003_auto_20201129_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='notifications',
            field=models.ManyToManyField(blank=True, to='ksa_books_app.Notification'),
        ),
    ]
