# Generated by Django 3.1.3 on 2020-12-01 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0004_auto_20201129_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('0', 'Comment'), ('1', 'New offer'), ('2', 'Sold to user'), ('3', 'Sold to other'), ('4', 'New want'), ('5', 'Buyer cancel'), ('6', 'Seller cancel')], max_length=1, null=True),
        ),
    ]
