# Generated by Django 3.1.2 on 2020-11-12 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0005_auto_20201106_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='secret',
            field=models.BooleanField(null=True),
        ),
    ]
