# Generated by Django 3.1.2 on 2020-11-12 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0006_comment_secret'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='studentuser',
            managers=[
            ],
        ),
    ]
