# Generated by Django 3.1.3 on 2020-12-02 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0006_auto_20201202_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='buyer_done_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='seller_done_time',
            field=models.DateTimeField(null=True),
        ),
    ]
