# Generated by Django 3.1.2 on 2020-11-15 01:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0008_auto_20201115_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='want_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
