# Generated by Django 3.1.2 on 2020-11-15 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0009_auto_20201115_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='want_users',
        ),
    ]
