# Generated by Django 3.1.2 on 2020-11-15 02:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0010_remove_offer_want_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='want_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
