# Generated by Django 3.1.2 on 2020-11-19 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0011_offer_want_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='unread_notification',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
