# Generated by Django 3.1.2 on 2020-11-20 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0012_auto_20201119_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data_offer1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ksa_books_app.offer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='data_user1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
