# Generated by Django 3.1.2 on 2020-11-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0014_auto_20201120_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='notify_books',
            field=models.ManyToManyField(to='ksa_books_app.Book'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[(0, 'Comment'), (1, 'New offer'), (2, 'Sold to user'), (3, 'Sold to other'), (4, 'New want')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
