# Generated by Django 3.1.2 on 2020-11-21 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0018_book_subject'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['subject'], 'permissions': (('load_data', 'Can load data'),)},
        ),
        migrations.AlterField(
            model_name='offer',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offer_buyer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='want_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
