# Generated by Django 3.1.2 on 2020-11-22 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0019_auto_20201121_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='group_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='공동구매 가격'),
        ),
        migrations.AlterField(
            model_name='book',
            name='list_price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='정가'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='receiver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data_offer1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ksa_books_app.offer'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='data_user1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='note_explain',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='worn_explain',
            field=models.TextField(blank=True, null=True, verbose_name='설명'),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='notify_books',
            field=models.ManyToManyField(blank=True, to='ksa_books_app.Book', verbose_name='알림을 받을 책'),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
