# Generated by Django 3.1.2 on 2020-11-22 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0020_auto_20201122_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_time']},
        ),
    ]
