# Generated by Django 3.1.2 on 2020-11-22 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0021_auto_20201122_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ksa_books_app.offer'),
        ),
    ]
