# Generated by Django 3.1.2 on 2020-11-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0022_auto_20201122_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
