# Generated by Django 3.1.2 on 2020-11-23 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0023_comment_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='other',
            field=models.TextField(blank=True, null=True, verbose_name='기타 내용'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
