# Generated by Django 3.1.3 on 2020-11-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0024_auto_20201123_0909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='notifications',
            field=models.ManyToManyField(to='ksa_books_app.Notification'),
        ),
    ]
