# Generated by Django 3.1.3 on 2020-11-25 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ksa_books_app', '0025_auto_20201124_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='courses',
            field=models.ManyToManyField(to='ksa_books_app.Course', verbose_name='과목'),
        ),
        migrations.AlterField(
            model_name='book',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ksa_books_app.subject', verbose_name='교과'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='과목명'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ksa_books_app.subject', verbose_name='교과'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=10, verbose_name='교과명'),
        ),
    ]
